### ISSUE TITLE
feature request appimage

### ISSUE THREAD

**Issue by freddii** [Cyborgscode/wifiscanner#1]
it would be nice to have an appimage of this application.

**Comment by Cyborgscode** [comment]
Hi,

sorry for the delay. 

AppImages, Snaps, Flatpaks, Dockercontainer aso. are things i do not support, as the concept of those os-independing startable "archives" is something i'm against. It would be hypocrite of me, to supply this sort of application, which btw.. would be bigger than the sole exe you really need ;)

BUT ... I will maybe open a rpm repo for some kinds of software i compile, as an interesting project  recently crossed my way ;) Which means, at least RPM based linuxoses will be able to get software precompiled and running.

**Comment by freddii** [comment]
ok, so i will close the feature request.

**Comment by freddii** [comment]
i found LinSSID in debian, that might also be usefull for me.
